name: check branch

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'feature/**'
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - 'master'
      - 'dev'
      - 'feature/**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: check

  
