name: check branch

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'feature/**'
  pull_request:
    types: 
      - opened
      - reopened
      - pushed
      - synchronize
      - ready_for_review
    branches:
      - 'master'
      - 'dev'
      - 'feature/**'

jobs:
  check:
    if: github.repository == 'EluvK/e-metrics-dw'
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo check

  
